README.md
src/main/java/com/trip/attraction/controller/AttractionController.java
src/main/java/com/trip/attraction/dto/AttractionDetailDto.java
src/main/java/com/trip/attraction/dto/AttractionDto.java
src/main/java/com/trip/attraction/dto/AttractionInitDataResponseDto.java
src/main/java/com/trip/attraction/dto/AttractioninitResponseDto.java
src/main/java/com/trip/attraction/dto/GuGunDto.java
src/main/java/com/trip/attraction/dto/PagedAttractionResponseDto.java
src/main/java/com/trip/attraction/dto/SidoDto.java
src/main/java/com/trip/attraction/mapper/AttractionMapper.java
src/main/java/com/trip/attraction/mapper/ContentTypeMapper.java
src/main/java/com/trip/attraction/mapper/SidoGunMapper.java
src/main/java/com/trip/attraction/service/AttractionService.java
src/main/java/com/trip/attraction/service/AttractionServiceImpl.java
src/main/resources/mapper/AttractionMapper.xml
src/main/resources/mapper/ContentTypeMapper.xml
src/main/resources/mapper/SidoGunMapper.xml

- 관광지 초기화면, 구군 조회, 관광지 조회, 관광지 상세 API구현
- 댓글 관련 부분 로직 추가 후 관광지 상세 API에 해당 내용 붙이기
- 좋아요 기능 구현(사용자 부분도)
close #1

[BE] Feature: Attract 조회 구현 #1

---

src/main/java/com/trip/attraction/mapper/AttractionMapper.java
src/main/java/com/trip/attraction/service/AttractionService.java
src/main/java/com/trip/attraction/service/AttractionServiceImpl.java
src/main/java/com/trip/favorite/controller/FavoriteController.java
src/main/java/com/trip/favorite/mapper/FavoriteMapper.java
src/main/java/com/trip/favorite/service/FavoriteService.java
src/main/java/com/trip/favorite/service/FavoriteServiceImpl.java
src/main/resources/mapper/AttractionMapper.xml
src/main/resources/mapper/FavoriteMapper.xml
src/main/resources/sql/Dump20241121_AllThings_FINAL.sql

- 사용자의 모든 북마크 조회 -> 조회시 페이징 처리
- 북마크 더미 데이터 추가

[BE] Refactoring: 북마크 조회 API 페이징 처리

---

src/main/java/com/trip/attraction/dto/AttractionDto.java
src/main/java/com/trip/attraction/mapper/AttractionMapper.java
src/main/java/com/trip/attraction/service/AttractionServiceImpl.java
src/main/java/com/trip/favorite/controller/FavoriteController.java
src/main/java/com/trip/schedule/controller/ScheduleController.java
src/main/resources/mapper/AttractionMapper.xml
src/main/resources/mapper/FavoriteMapper.xml
src/main/resources/mapper/ScheduleMapper.xml
src/main/resources/sql/Dump20241121_AllThings_FINAL.sql

- user 연관된 테이블에 casacde 옵션 추가
- favorites dto, url 수정
- schedules url 수정
- 관광지 정렬 쿼리문 변경
- Attraction 정렬시에 파라미터 값: title, likes, views

[BE] Refactoring: 북마크 및 여행일정 DTO, URL path 수정 및 관광지 정렬 방식 수정

---

src/main/java/com/trip/ai/controller/AiController.java

- 이미지 생성 프롬프트 작성 및 url 반환 테스트 실행
- properties ai부분 image형식으로 수정 필요(secrets.properties 항목 참고)

[BE] Feature: Image 생성 AI 프롬프트 추가

---

src/main/java/com/trip/attraction/controller/AttractionController.java
src/main/java/com/trip/attraction/dto/AttractionDetailDto.java
src/main/java/com/trip/attraction/dto/AttractionDetailResponseDto.java
src/main/java/com/trip/attraction/dto/AttractionDto.java
src/main/java/com/trip/attraction/mapper/AttractionMapper.java
src/main/java/com/trip/attraction/service/AttractionService.java
src/main/java/com/trip/attraction/service/AttractionServiceImpl.java
src/main/java/com/trip/config/WebConfig.java
src/main/java/com/trip/favorite/controller/FavoriteController.java
src/main/java/com/trip/favorite/mapper/FavoriteMapper.java
src/main/java/com/trip/favorite/service/FavoriteService.java
src/main/java/com/trip/favorite/service/FavoriteServiceImpl.java
src/main/resources/mapper/AttractionMapper.xml
src/main/resources/mapper/FavoriteMapper.xml

-  관광지 조회시 좋아요 여부 파악 API 구현
-  search/init 시에 페이지 파라미터 가능하도록 변경
- 관광지 목록 조회 dto에 contentType 추가 필요

[BE] Feature: 관광지 조회시 좋아요 여부 파악 API 구현

---

src/main/java/com/trip/weather/controller/WeatherController.java
src/main/java/com/trip/weather/dto/WeatherRequestDto.java
src/main/java/com/trip/weather/dto/WeatherResponseDto.java
src/main/java/com/trip/weather/service/WeatherService.java

[BE] Feature: 날씨 공공 API 연결 확인

---

src/main/java/com/trip/attraction/controller/AttractionController.java
src/main/java/com/trip/attraction/service/AttractionService.java
src/main/java/com/trip/attraction/service/AttractionServiceImpl.java
src/main/java/com/trip/member/controller/MemberController.java
src/main/java/com/trip/member/dto/LoginResponseDTO.java
src/main/resources/mapper/MemberMapper.xml

- sido목록 반환 API 구현
- 로그인시 회원 address 변수 반환

[BE] feat: Sido조회 API 구현

---

src/main/java/com/trip/question/controller/QuestionController.java
src/main/java/com/trip/question/mapper/QuestionMapper.java
src/main/java/com/trip/question/service/QuestionService.java
src/main/resources/mapper/QuestionMapper.xml

refactor: 관리자 모든 질문 조회 가능 #49

---

pom.xml
src/main/java/com/trip/ai/dto/WeatherAndClothesResponseDto.java
src/main/java/com/trip/ai/service/AIServiceImpl.java
src/main/resources/sql/Dump20241121_AllThings_FINAL.sql

-  API DTO 수정 및 챗모델 프롬프트 추가
- 더미데이터 추가

[BE] Feature: 여행 일정을 통한 AI 활용 기능에 준비물도 포함

---

.env
index.html
src/api/axios.js

- BaseURL: localhost -> domain name 으로 변경
- .env파일 ignore 추가 및 api키 재발급 필요(노출의 이유)

config: baseURL방식 변경 및 env파일 설정 #62

---

pom.xml
src/main/java/com/trip/config/WebConfig.java

- https적용 시킨 DNS cors 설정 변경 완료

[BE] Fix: https 적용에 따른 로그인 인증 에러 해결

---

.github/workflows/deploy-backend.yml
src/main/resources/application.properties

- properites 추가(key = value 형태)
- workflow 작성

[BE] Feature: Backend CI 적용 

---

src/main/java/com/trip/config/SwaggerConfig.java
src/main/java/com/trip/config/SwaggerInterceptor.java
src/main/java/com/trip/config/WebConfig.java
src/main/resources/application.properties

-  Swagger 서버 cors 에러 해결
-  Swagger DB 스키마 분리
- GET, POST만 사용가능 -> 따라서 Create POST는 요청하지 않도록 주의바랍니다

[BE] Feature: swagger 서버 cors 에러 해결 및 DB 분리 

---

.github/workflows/deploy.yml
lighthouserc.json

-  LightHouse Workflow작성
-  S3에 저장 로직 작성 및 S3 설정

[FE] feat: Workflow에 LightHouse 추가 #78

---

.github/workflows/deploy-backend.yml
src/main/resources/application.properties

-  스프링 실행 이후 서버 작동 확인 flow 추가
-  오류 배포 test 와 성공 배포 test 진행

[CI] BE workflow 수정

---

src/views/auth/AuthRegisterView.vue

[FE] hotfix: 회원가입 오류 수정 

---

src/main/java/com/trip/attraction/service/AttractionService.java
src/main/java/com/trip/attraction/service/AttractionServiceImpl.java
src/main/java/com/trip/comment/controller/CommentController.java
src/main/resources/application.properties

- 불필요한 sql출력문 제거
- session id 타입 변경

[BE]fix: "comment생성 처리방식 변경" 

---

pom.xml
src/main/java/com/trip/ai/controller/AIController.java
src/main/java/com/trip/ai/service/AIServiceImpl.java
src/main/java/com/trip/review/service/ReviewSerivce.java
src/main/java/com/trip/review/util/S3Util.java
src/main/java/com/trip/translation/dto/Translation.java
src/main/java/com/trip/translation/dto/TranslationResponse.java
src/main/java/com/trip/translation/service/TranslationService.java
src/main/java/com/trip/translation/service/TranslationServiceImpl.java
src/main/resources/application.properties

- Spring AI모델 전환(dalle 3 -> Stable Diffusion)
- 프롬프트 작성시 번역을 위한 번역 API DeepL적용
- 비동기 방식을 적용을 통한 시간 단축
- 초기 dalle3 테스트, 약 28초
- Stable Diffusion 적용, 약 11초
- 비동기 적용, 약 8초

[BE] refact: AI 모델 전환 #75

---

.github/workflows/deploy-backend.yml

- 코드 증가량에 따라 서버 실행 시간 증가 -> healthcheck 시간 변경 필요
- workflow 서버 정상 작동 이후 health check 오류 확인 및 수정

[CI] hotfix: BE 자동배포 이후 검증 단계에서의 오류 해결 #109

---

index.html
src/views/auth/AuthRegisterView.vue

- 피비콘 반영
- 회원가입시 이름에 특수문자 에러 메시지 추가

[refact] 아이콘 반영, 회원가입 이름 수정

---

src/views/auth/AuthRegisterView.vue

회원가입 CSS -> global css 적용
예외처리

refact : 회원가입단 css 변경, 예외처리 #91
